[package]
name = "terasoft-notebull"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "keys"
path = "src/listen_global_keys.rs"

[dependencies]
rdev = "0.5.2"
enigo = "0.1.2"
